# Generated by Django 3.2.13 on 2022-04-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
