# Generated by Django 3.2.13 on 2022-04-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_contacts_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Client',
        ),
    ]
