# Generated by Django 3.2.13 on 2022-04-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_contact_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depositID', models.CharField(max_length=255)),
                ('applicationId', models.CharField(max_length=255)),
                ('transactionAmount', models.CharField(max_length=255)),
                ('transactionStatus', models.CharField(max_length=255)),
                ('transactionDate', models.CharField(max_length=255)),
                ('datetime', models.CharField(max_length=255)),
                ('transactionType', models.CharField(max_length=255)),
                ('currencyCode', models.CharField(max_length=255)),
            ],
        ),
    ]
